/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f5',
        'inverse-on-surface': '#f2f0ed',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1c1a',
        'surface-tint': '#316289',
        'secondary-container': '#b6edc2',
        primary: '#074469',
        'on-secondary-fixed': '#00210e',
        'primary-fixed-dim': '#9ccbf7',
        'surface-bright': '#fbf9f5',
        'on-tertiary-fixed': '#410004',
        'on-primary-fixed': '#001d32',
        outline: '#72787f',
        'on-background': '#1b1c1a',
        'secondary-fixed-dim': '#9dd3aa',
        'outline-variant': '#E5E0D5',
        'on-secondary-container': '#3b6d4b',
        'surface-variant': '#e4e2de',
        'on-tertiary-fixed-variant': '#8b191d',
        'error-container': '#ffdad6',
        'primary-fixed': '#cde5ff',
        'tertiary-container': '#a32c2c',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'secondary-fixed': '#b9efc5',
        'tertiary-fixed-dim': '#ffb3ae',
        error: '#ba1a1a',
        'surface-container-high': '#eae8e4',
        'surface-container-low': '#f5f3ef',
        'tertiary-fixed': '#ffdad7',
        'on-tertiary-container': '#ffbfba',
        'surface-container-highest': '#e4e2de',
        'on-error': '#ffffff',
        'on-primary-container': '#a5d4ff',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#1e5031',
        background: '#fbf9f5',
        tertiary: '#821218',
        'surface-dim': '#dbdad6',
        'inverse-primary': '#9ccbf7',
        'primary-container': '#2a5c82',
        'inverse-surface': '#30312e',
        'on-primary-fixed-variant': '#124a6f',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#41474e',
        secondary: '#376847',
        'surface-container': '#efeeea',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        base: '4px',
        gutter: '16px',
        xs: '4px',
        'container-margin': '16px',
        sm: '8px',
        xl: '32px',
        md: '16px',
      },
      fontFamily: {
        'body-md': ['Work Sans'],
        'display-md': ['Plus Jakarta Sans'],
        'display-md-mobile': ['Plus Jakarta Sans'],
        'amount-lg': ['Work Sans'],
        'body-lg': ['Work Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Work Sans'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-md-mobile': ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'amount-lg': ['24px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
